### ISSUE TITLE
.Drive: Image.MediaMetadata

### ISSUE THREAD

**Issue by ronimizy** [kysect/CentumFramework#41]
## Tasks
- [ ] Create `class Image: File`
- [ ] Create File Factory and integrate it into `DriveService`
- [ ] Create `class MediaMetadata` attribute it’s properties 
- [ ] Fill `MediaMetadata` properties with documentation
- [ ] Create fetching test

## class MediaMetadata
- [ ]  width
- [ ]  height
- [ ]  rotation
- [ ]  class Location(latitude, longitude, altitude)
- [ ]  time
- [ ]  cameraMake
- [ ]  cameraModel
- [ ]  exposureTime
- [ ]  aperture
- [ ]  flashUsed
- [ ]  focalLength
- [ ]  isoSpeed
- [ ]  meteringMode
- [ ]  sensor
- [ ] exposureMode
- [ ] colorSpace
- [ ] whiteBalance
- [ ] exposureBias
- [ ] maxAppertureValue
- [ ] subjectDistance
- [ ] lens
