### ISSUE TITLE
.Drive: VideoFile.MediaMetadata

### ISSUE THREAD

**Issue by ronimizy** [kysect/CentumFramework#42]
##Tasks 
- [ ] Create `class VideoFile: File`
- [ ] Create File Factory and integrate it into `DriveService`
- [ ] Create `class VideoMediaData` and attribute it’s properties
- [ ] Fill `VideoMediaData` properties with documentation (///)
- [ ] Create fetching test

## class VideoMediaData
- [ ] width
- [ ] height 
- [ ] durationMs

## Documentation 
https://developers.google.com/drive/api/v3/reference/files?hl=en_US#resource-representations
