### ISSUE TITLE
.Drive: File.Capabilities

### ISSUE THREAD

**Issue by ronimizy** [kysect/CentumFramework#43]
## Tasks
- [ ] Create `class FileCapabilities` and attribute it’s properties 
- [ ] Fill `FileCapabilities` properties with documentation (///)
- [ ] Add and attribute `FileCapabilities Capabilities` to `File` and attribute it
- [ ] Create fetching test

## [Flags] enum FileCapabilities
- [ ] canEdit
- [ ] canComment
- [ ] canShare
- [ ] canCopy
- [ ] canReadRevisions
- [ ] canAddChildren
- [ ] canDelete
- [ ] canDownload
- [ ] canListChildren
- [ ] canRemoveChildren
- [ ] canRename
- [ ] canTrash
- [ ] canUntrash

## Documentation 
https://developers.google.com/drive/api/v3/reference/files?hl=en_US#resource-representations
