### ISSUE TITLE
.Drive ShortcutFile.Details

### ISSUE THREAD

**Issue by ronimizy** [kysect/CentumFramework#44]
## Tasks
- [ ]  Create `class ShortcutFile: File`
- [ ] Integrate it into a `FileFactory`
- [ ] Create `class ShortcutDetails` and attribute it’s values
- [ ] Add a `ShortcutDetails Details` into `ShortcutFile` and attribute it
- [ ] Fill all the created properties with documentation `///`

## class ShortcutDetails
- [ ] targetId
- [ ] targetType

## Documentation 
https://developers.google.com/drive/api/v3/reference/files?hl=en_US#resource-representations
