### ISSUE TITLE
.Drive: uncategorized File fields

### ISSUE THREAD

**Issue by ronimizy** [kysect/CentumFramework#46]
## Tasks
- [ ] Create properties and attribute them
- [ ] Fill all the properties with documentation 
- [ ] Create fetching test

## Fields
- [ ] explositlyTrashed
- [ ] properties
- [ ] appProperties
- [ ] spaces
- [ ] version
- [ ] webContentLink
- [ ] webViewLink
- [ ] iconLink
- [ ] thumbnailLink
- [ ] viewedByMe
- [ ] lastViewByMeTime
- [ ] lastModifiedByMeTime
- [ ] sharedWithMeTime
- [ ] shared
- [ ] ownedByMe
- [ ] writersCanShare
- [ ] permissions
- [ ] fullFileExtension
- [ ] fileExtension
- [ ] md5Checksum
- [ ] quotaBytesUsed
- [ ] headRevisionId
- [ ] isAppAuthorized
- [ ] hasThumbnail
- [ ] thumbnailVersion
- [ ] modifiedByMe
- [ ] trashedTime
- [ ] permissionIds
- [ ] exportLinks
- [ ] driveId
- [ ] resourceKey

## Documentation 
https://developers.google.com/drive/api/v3/reference/files?hl=en_US#resource-representations
