### ISSUE TITLE
.Drive: File.ContentRestrictions

### ISSUE THREAD

**Issue by ronimizy** [kysect/CentumFramework#47]
## Dependencies 
- #37 -> ` _ `

## Tasks
- [ ] Create `class ContentRestriction` and attribute it’s properties
- [ ] Add and attribute `File.ContentRestrictions` 
- [ ] Document all the created properties
- [ ] Add fetching test for all the created properties

## class ContentRestriction
- [ ] IsReadonly
- [ ] Reason
- [ ] RestrictingUser: User
- [ ] RestrictionTime
- [ ] Type

## Documentation 
https://developers.google.com/drive/api/v3/reference/files?hl=en_US#resource-representations
