### ISSUE TITLE
.Drive & .Sheets: test refactoring

### ISSUE THREAD

**Issue by ronimizy** [kysect/CentumFramework#51]
## Tasks
- [ ] Refactor tests so all the functions of entities and services would be covered
- [ ] Refactor tests so all the actions would be covered
- [ ] .Drive: Refactor tests so all the "Query" code would be covered
- [ ] .Sheets: Refactor tests so all the "Indices" code would be covered 
- [ ] .Utility: Add `AccessCache` tests
